import os 
from github import Github
from github import GithubException 
from datetime import datetime
from typing import Optional, Dict, Any, List


## EPITOME --> DO IT FOR WHEN ANY ERROR OR ANY ISSUE RAISE IN THE GITHUB AND AUTOMATICALLY GET THAT ISSUE PASSED INTO ORCHESTRATOR.PY
class GitHubIssueCreator:
    """
        Github Issue Creator class
    """

    def __init__(self,token:str= None, repo_name:str = None):
        """
            Initialize Github Connection 
        """
        self.token = token or os.getenv("GITHUB_TOKEN")
        ## check for validation 
        if not self.token:
            raise ValueError("GITHUB_TOKEN is not set")
        
        self.repo_name = repo_name or os.getenv("REPO_NAME")
        ## check for validation 
        if not self.repo_name:
            raise ValueError("REPO_NAME is not set")
        

        ## connection to github
        self.github = Github(self.token)

        try:
            ## getting the repo 
            self.repo = self.github.get_repo(self.repo_name)
            print(f"Connected to {self.repo_name}")
        except GithubException as e:
            print(f"Failed to connect :{e}")
            raise
        
    def create_issue(
        self,
        title: str,
        description : str,
        labels : List[str] = None,
        assignees : List[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """
            Create a github issue with analysis result 
        """
        try:
            ## create a issue 
            issue = self.repo.create_issue(
                title = title,
                body = description,
                labels = labels or [],
                assignees = assignees or  [],
            )

            print(f"Created Github Issue {issue.html_url}")
            return {
                "number": issue.number,
                "url": issue.html_url,
                "title": issue.title,
                "state": issue.state,
                "created_at": issue.created_at.isoformat(),
            }
        except GithubException as e:
            print(f"Failed to create Issue", e)
            return None
        

    def add_comment(self, issue_number:int, comment:str) -> bool :
        """
            Add a comment to a github issue 
        """
        try:
            issue = self.repo.get_issue(number=issue_number)
            issue.create_comment(comment)
            print(f"Added comment to issue {issue_number}")
            return True
        except GithubException as e:
            print(f"Failed to add comment to issue {issue_number}", e)
            return False
        

    def close_issue(self, issue_number:int) -> bool :
        """
            Close a github issue 
        """
        try:
            issue = self.repo.get_issue(number = issue_number)
            issue.edit(state ="closed")
            print(f"Closed issue {issue_number}")
            return True
        except GithubException as e:
            print(f"Failed to close issue {issue_number}", e)
            return False
    
    def list_open_issues(self) -> List[Dict[str, Any]]:
        """
            List all open issues in a github repo 
        """
        try:
            issues = self.repo.get_issues(state="open")
            result = []

            for issue in issues[:10]: ## limited to 10 only
                result.append({
                    "number": issue.number,
                    "title" : issue.title,
                    "url" : issue.html_url,
                    "created_at" : issue.created_at.isoformat()
                })
            return result
        except GithubException as e:
            print(f"Failed to list issues", e)
            return []
        
    def create_issue_from_analysis(
        repo_url: str,
        description: str,
        root_cause: str,
        affected_file: str,
        confidence: float,
        context_lines: List[Dict]
    ) -> Optional[str]:
        """
            Create a github issue from analysis result 
        """
          
        # Format issue title
        title = f"🐛 Auto-detected: {description[:80]}..."
        
        # Format issue body with markdown
        body = f"""## 🔍 Incident Description
        {description}

        ## 🎯 Root Cause
        **{root_cause}**

        ## 📁 Affected File
        `{affected_file}`

        ## 📊 Confidence
        **{confidence:.1%}**

        ## 📄 Context
        """
            
            # Add context lines
        for ctx in context_lines[:5]:
            body += f"\nLine {ctx.get('line_number', '?')}: `{ctx.get('text', '')}`"
        
        # Add suggested action
        body += f"""

        ## 🛠️ Suggested Action
        1. Review the affected file
        2. Check the context lines above
        3. Apply appropriate fix
        4. Close this issue when fixed

        ---
        *Auto-generated by Incident-Fix-Agent at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
        """
    
        # Extract repo name from URL
        # Example: https://github.com/username/repo-name.git
        repo_name = repo_url.replace('https://github.com/', '').replace('.git', '')
        
        # Create issue
        creator = GitHubIssueCreator(repo_name=repo_name)
        result = creator.create_issue(
            title=title,
            description=body,
            labels=["bug", "auto-detected"]
        )
        
        return result["url"] if result else None